### PR TITLE
More robust GMS 2.2.2.302 and PSEM checks

### LINKED ISSUE #1381: Loading Warning when Opening some games
### Describe the bug

image

Some data.win files are having this problem, not really sure what the cause is. But in this case it's the [Destructivator 2 Demo](https://gamejolt.com/games/destructivator2demo/309337)

### Reproducing steps

1. Open UndertaleModTool
2. Open the game's  `data.win` file
3. `Loading warning` pops up

### Setup Details

1. UndertaleModTool Version: Both bleeding edge and Stable 0.5.1.0
2. Operating System: Windows 10 Pro 22H2 (Build 19045.2965)
3. Gamemaker Game: https://gamejolt.com/games/destructivator2demo/309337
4. Gamemaker Game Version: Unknown

### LINKED ISSUE #1554: Load error while reading chunk
### Describe the bug

When trying to load the data file, the mod tool spits out an error. 
屏幕截图 2023-11-29 114929
屏幕截图 2023-11-29 6

### Reproducing steps

1.Open UndertaleModTool
2.Load the game
3.Error shows up

### Setup Details

UndertaleModTool 0.5.1.0 (Bleeding Edge)
Windows 10
Game:Dungeon Raiders v3.68.2 (https://erohz.itch.io/tpdr)

### PR DESCRIPTION
**Pull request by Jacky720**
## Description
Changes the GMS 2.2.2.302 check to iterate over all rooms, thus not failing on "Destructivator 2 Demo" (which has no objects in the first room and thus passes over the old check without detecting the version). Closes #1381.

Additionally, implements new PSEM (Particle System EMitter) checks to identify GM2023.4, GM2023.6, and GM2023.8, as well as adding the new values to both UndertaleParticleSystemEmitter and its corresponding editor in the GUI. Closes #1554.

### Caveats
Limited testing. I still don't fully understand the point of UnserializeObjectCount.

### Notes
2.2.2.302 seems like it would be a needlessly precise version, but if we're internally consistent it doesn't look like a problem.

### CODE REVIEW

**Comment by Miepee** [comment]
havent cehcked diff yet:
> which has no objects in the first room and thus passes over the old check without detecting the version

What if all rooms have no objects?

**Comment by Jacky720** [comment]
Then the versions are functionally indistinguishable, it'll load correctly as 2.2.1, and the correct fix is to change the version number in General Info before saving.

File: UndertaleModLib/UndertaleChunks.cs [hunk 1]
```diff
@@ -792,6 +796,58 @@ private void CheckForEffectData(UndertaleReader reader)
 
             checkedFor2022_1 = true;
         }
+
+        private static bool checkedForGMS2_2_2_302;
+        private void CheckForImageSpeed(UndertaleReader reader)
+        {
+            // Check the size of the first GameObject in a room
+            if (reader.undertaleData.IsGameMaker2() && !reader.undertaleData.IsVersionAtLeast(2, 2, 2, 302))
```
Comment (Miepee) [inline UndertaleModLib/UndertaleChunks.cs:804]: invert this condition please

File: UndertaleModLib/UndertaleChunks.cs [hunk 2]
```diff
@@ -792,6 +796,58 @@ private void CheckForEffectData(UndertaleReader reader)
...
+                        // Check performed, one way or the other
+                        break;
+                    }
+                    // continue to next room if there are no objects
+                }
+
+                reader.Position = returnTo;
+            }
+
+            checkedForGMS2_2_2_302 = true;
```
[the remark this answers is not in the document]
Comment (Jacky720) [reply UndertaleModLib/UndertaleChunks.cs:849]: No, because if the check is able to immediately terminate by seeing the version is too low or already there, it still did the check, and should set the checkedFor... variable to avoid repeating the check.

**Comment by colinator27** [comment]
Looks pretty complete to me. Just need verification that this has been adequately tested, and then it should be good to merge.

File: UndertaleModLib/Models/UndertaleParticleSystem.cs [hunk 3]
```diff
@@ -120,13 +137,23 @@ protected void OnPropertyChanged([CallerMemberName] string name = null)
...
-    public float SizeMin { get; set; } = 1;
+    // 2023.8
+    public float SizeMinX { get; set; } = 1;
+    public float SizeMaxX { get; set; } = 1;
+    public float SizeIncreaseX { get; set; }
+    public float SizeWiggleX { get; set; }
+    public float SizeMinY { get; set; } = 1;
+    public float SizeMaxY { get; set; } = 1;
+    public float SizeIncreaseY { get; set; }
+    public float SizeWiggleY { get; set; }
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleParticleSystem.cs:148]: Can you either add documentation for these, or add a todo to add documentation?

File: UndertaleModLib/Models/UndertaleParticleSystem.cs [hunk 4]
```diff
@@ -120,13 +137,23 @@ protected void OnPropertyChanged([CallerMemberName] string name = null)
...
-    public float SizeMax { get; set; } = 1;
+    public float SizeMin { get => (SizeMinX + SizeMinY) / 2; set { SizeMinX = value; SizeMinY = value; } }
 
-    public float SizeIncrease { get; set; }
+    public float SizeMax { get => (SizeMaxX + SizeMaxY) / 2; set { SizeMaxX = value; SizeMaxY = value; } }
 
-    public float SizeWiggle { get; set; }
+    public float SizeIncrease { get => (SizeIncreaseX + SizeIncreaseY) / 2; set { SizeIncreaseX = value; SizeIncreaseY = value; } }
+
+    public float SizeWiggle { get => (SizeWiggleX + SizeWiggleY) / 2; set { SizeWiggleX = value; SizeWiggleY = value; } }
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleParticleSystem.cs:156]: same for these

File: UndertaleModLib/Models/UndertaleParticleSystem.cs [hunk 5]
```diff
@@ -323,4 +418,9 @@ public enum TextureEnum
         Smoke = 12,
         Snow = 13
     }
+    public enum TimeUnitEnum
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleParticleSystem.cs:421]: here too

File: UndertaleModLib/UndertaleChunks.cs [hunk 6]
```diff
@@ -714,84 +718,145 @@ internal override uint UnserializeObjectCount(UndertaleReader reader)
...
-                                break;
-                        }
-                    }
-                }
+                // Actually perform the length checks, depending on layer data
+                reader.AbsPosition = jumpOffset;
 
-                reader.Position = returnTo;
+                LayerType layerType = (LayerType)reader.ReadInt32();
+                // Basically the switch's default, as each successful switch case terminates the loop
```
Comment (Miepee) [inline UndertaleModLib/UndertaleChunks.cs:761]: *as well as?

File: UndertaleModLib/UndertaleChunks.cs [hunk 7]
```diff
@@ -1066,69 +1131,75 @@ public class UndertaleChunkTXTR : UndertaleListChunk<UndertaleEmbeddedTexture>
...
+                // Also check for 2022.5 format
+                reader.Position = positionToReturn + 4;
+                for (uint i = 0; i < texCount; i++)
                 {
-                    // Also check for 2022.5 format
-                    reader.Position = positionToReturn + 4;
-                    for (uint i = 0; i < texCount; i++)
+                    // Go to each texture, and then to each texture's data
+                    reader.Position = positionToReturn + 4 + (i * 4);
+                    reader.AbsPosition = reader.ReadUInt32() + 12; // go to texture, at an offset
```
Comment (Miepee) [inline UndertaleModLib/UndertaleChunks.cs:1167]: Uppercase Go please

File: UndertaleModLib/UndertaleChunks.cs [hunk 8]
```diff
@@ -1066,69 +1131,75 @@ public class UndertaleChunkTXTR : UndertaleListChunk<UndertaleEmbeddedTexture>
...
+                    reader.AbsPosition = reader.ReadUInt32(); // go to texture data
```
Comment (Miepee) [inline UndertaleModLib/UndertaleChunks.cs:1168]: Uppercase Go please

File: UndertaleModLib/UndertaleChunks.cs [hunk 9]
```diff
@@ -1733,6 +1802,93 @@ internal override uint UnserializeObjectCount(UndertaleReader reader)
...
+                    reader.undertaleData.SetGMS2Version(2023, 4);
+            }
+
+            if (count == 0) // Nothing more to do here, unfortunately
+            {
+                reader.AbsPosition = positionToReturn;
+                checkedPsemVersion = true;
+                return;
+            }
+
```
Comment (Miepee) [inline UndertaleModLib/UndertaleChunks.cs:1834]: i would remove this newline for nicer readability

File: UndertaleModLib/UndertaleChunks.cs [hunk 10]
```diff
@@ -1733,6 +1802,93 @@ internal override uint UnserializeObjectCount(UndertaleReader reader)
...
+            }
+            else if (secondPtr - firstPtr == 0xBC)
+            {
+                if (!reader.undertaleData.IsVersionAtLeast(2023, 4))
+                    reader.undertaleData.SetGMS2Version(2023, 4);
+            }
+            else if (secondPtr - firstPtr != 0xB0) // 2023.2
+            {
+                reader.AbsPosition = positionToReturn;
+                throw new IOException("Unrecognized PSEM size with " + count.ToString() + " elements");
```
Comment (Miepee) [inline UndertaleModLib/UndertaleChunks.cs:1885]: Is this tostring necessary? wouldn't it implicility casted?

File: UndertaleModLib/UndertaleChunks.cs (hunk 6 above)
Comment (Jacky720) [reply UndertaleModLib/UndertaleChunks.cs:761]: No, just "as". I could substitute "because", perhaps.

Comment (Miepee) [reply UndertaleModLib/UndertaleChunks.cs:761]: ah in that sense. might be more understandable.

**Comment by SantiHSilva** [comment]
Missing parenthesis in ExportAllStrings.csx

image

**Comment by Jacky720** [comment]
That sounds unrelated to this pull request.

**Comment by Anti-Apple4life** [comment]
When trying to open Undertale Yellow with the modified UndertaleModCli, this error is thrown:

```
Trying to load file: '/home/user/Desktop/Undertale Yellow/data.win'
The type initializer for 'Gdip' threw an exception.
at 019AB337 while reading object UndertaleModLib.Models.UndertaleEmbeddedTexture+TexData in chunk TXTR
```

**Comment by b3nj4m4n** [comment]
i don't usually come to github :P how do i install this to utmt trying to look at the new Boom! Buster demo's unused stuff

**Comment by Dobby233Liu** [comment]
The PR has been merged, so just download the [bleeding edge](https://github.com/UnderminersTeam/UndertaleModTool/releases/bleeding-edge) `GUI-windows-latest-Release-isBundled-true-isSingleFile-true.zip` version
