### PR TITLE
A fix of the object ID label.

### LINKED ISSUE #999: Object ID is "N/A" for some types of objects.
### Describe the bug

Object ID label displays "N/A" when you open `UndertaleString` or `UndertaleCode`.

### Reproducing steps

1. Open `UndertaleString` or `UndertaleCode`
2. Object ID label (in the bottom right corner) is "N/A".

### Setup Details

1. UndertaleModTool version - commit https://github.com/krzys-h/UndertaleModTool/commit/765cf57ec86d129cade1d03e70bc476ff1f91dd5.

### PR DESCRIPTION
**Pull request by VladiStep**
## Description
The object ID label now displays an object ID for more types - `UndertaleCode` and `UndertaleString`.
Also, added `UndertaleData.ListProperties` for ease of reflection.

Closes #999

### CODE REVIEW

File: UndertaleModLib/UndertaleData.cs [hunk 1]
```diff
@@ -384,6 +384,22 @@ public class UndertaleData : IDisposable
         /// </summary>
         public bool GMLCacheIsReady { get; set; } = true;
 
+        /// <summary>
+        /// An array of a <see cref="UndertaleData"/> properties with <see cref="IList{T}"/> type.
```
Comment (Miepee) [inline UndertaleModLib/UndertaleData.cs:388]:
```suggestion
        /// An array of a <see cref="UndertaleData"/> properties with <see cref="IList{T}"/> as their type.
```

File: UndertaleModLib/UndertaleData.cs [hunk 2]
```diff
@@ -384,6 +384,22 @@ public class UndertaleData : IDisposable
...
+        /// </summary>
+        public PropertyInfo[] ListProperties { get; private set; }
```
Comment (Miepee) [inline UndertaleModLib/UndertaleData.cs:390]: Name is IMO a bit confusing. Based solely on the name, this sounds like this is a *list* of *all* Properties in UnderaleData.
This is neither a list tho, nor does it contain all properties.
Maybe name it something along the lines of `AllListProperties` ?

File: UndertaleModLib/UndertaleData.cs [hunk 3]
```diff
@@ -411,49 +427,22 @@ public UndertaleNamedResource ByName(string name, bool ignoreCase = false)
...
-            if (obj is UndertaleEmbeddedAudio)
-                return EmbeddedAudio.IndexOf(obj as UndertaleEmbeddedAudio);
-            if (obj is UndertaleEmbeddedTexture)
-                return EmbeddedTextures.IndexOf(obj as UndertaleEmbeddedTexture);
-            if (obj is UndertaleTexturePageItem)
-                return TexturePageItems.IndexOf(obj as UndertaleTexturePageItem);
-            if (obj is UndertaleAudioGroup)
-                return AudioGroups.IndexOf(obj as UndertaleAudioGroup);
+            Type objType = obj.GetType();
+            PropertyInfo objListProp = ListProperties.FirstOrDefault(x => x.PropertyType.GetGenericArguments()[0] == objType);
```
Comment (Miepee) [inline UndertaleModLib/UndertaleData.cs:440]: Would call this `objListPropInfo`

File: UndertaleModTool/MainWindow.xaml.cs [hunk 4]
```diff
@@ -3081,8 +3081,17 @@ private void SearchBox_TextChanged(object sender, TextChangedEventArgs e)
 
         public void UpdateObjectLabel(object obj)
         {
-            int foundIndex = obj is UndertaleNamedResource ? Data.IndexOf(obj as UndertaleNamedResource, false) : -1;
-            SetIDString(foundIndex == -1 ? "None" : (foundIndex == -2 ? "N/A" : Convert.ToString(foundIndex)));
+            int foundIndex = obj is UndertaleResource res
+                             ? Data.IndexOf(res, false)
+                             : -1;
```
Comment (Miepee) [inline UndertaleModTool/MainWindow.xaml.cs:3086]: This looks short enough that it can be on one line.

File: UndertaleModTool/MainWindow.xaml.cs [hunk 5]
```diff
@@ -3081,8 +3081,17 @@ private void SearchBox_TextChanged(object sender, TextChangedEventArgs e)
...
+            string idString = foundIndex == -1
+                              ? "None"
+                              : (foundIndex == -2
+                                 ? "N/A"
+                                 : Convert.ToString(foundIndex)
+                                );
```
Comment (Miepee) [inline UndertaleModTool/MainWindow.xaml.cs:3092]: I would personally use if elses here, instead of forcing ? : operators and make it less readable.

File: UndertaleModLib/UndertaleData.cs (hunk 2 above)
Comment (VladiStep) [reply UndertaleModLib/UndertaleData.cs:390]: If this was a list of all properties, then it would be named `Properties` or `PropertiesList`.
Also, there's a description for it.

So, I'm not sure if it should be 'AllListProperties` or not.

Comment (Miepee) [reply UndertaleModLib/UndertaleData.cs:390]: > If this was a list of all properties, then it would be named `Properties` or `PropertiesList`

This is heavily context dependant.

> Also, there's a description for it.

You don't always see the description. The name should be understandable enough on its own to a certain extent.

File: UndertaleModTool/MainWindow.xaml.cs [hunk 6]
```diff
@@ -3081,15 +3081,18 @@ private void SearchBox_TextChanged(object sender, TextChangedEventArgs e)
...
+
+            if (foundIndex == -1)
+                idString = "None";
+            else 
+            {
+                if (foundIndex == -2)
+                    idString = "N/A";
+                else
+                    idString = Convert.ToString(foundIndex);
+            }
```
Comment (Miepee) [inline UndertaleModTool/MainWindow.xaml.cs:3095]:
```cs
if (index == -1) ...
else if (index == -2) ...
else ...
```

**Review by Miepee — APPROVED** [review]
