### PR TITLE
Sprite origin fixes (and more)

### LINKED ISSUE #623: Changing the origin of Deltarune Chapter 2 sprites saves the changes, but doesn't affect anything in-game
Changing Kris's sprite in Chapter 1 (SURVEY_PROGRAM) works fine:
image
However, doing the exact same thing in Chapter 1&2 does nothing:
image
Even though UTMT shows the origin changed when closing and reopening the game:
image

### PR DESCRIPTION
**Pull request by VladiStep**
Room editor changes:

1. **Position of rotated/scaled `GameObject` and `SpriteInstance` are now properly displayed.**
2. **Sprite origin fields in the sprite editor now work _(with sprite origin wrappers)_.**
3. Added descriptions to some properties _(and modified existing)_.
4. Removed redundant converters: `ObjCenterXConverter`, `ObjCenterYConverter` and `ObjXOffsetConverter`.
5. Added `NegateNumberConverter`.
6. Suppressed `Bitmap`-related warnings in _"UndertaleCachedImageLoader.cs"_ and replaced with TODO.
7. _"Backgrounds & tile sets"_ item title changes to _"Tile sets"_ on GMS 2 games.
8. **Fixed bug that prevented adding sprite to a new sprite instance.**
9. New sprite instances have unique names _("graphic_XXXXXXXX", as in GameMaker Studio: 2)_.
10. Tiles are now properly updating on their sprite change.
11. Removed `GetBGColorLayer()` and integrated its contents into `BGColorLayer`.

Closes #623

### CODE REVIEW

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 1]
```diff
@@ -166,20 +166,26 @@ public enum RoomEntryFlags : uint
...
-                                    && l.BackgroundData.Color != 0)
-                           .OrderBy(l => l?.LayerDepth ?? 0)
-                           .FirstOrDefault();
-        }
         public void UpdateBGColorLayer() => OnPropertyChanged("BGColorLayer");
 
         /// <summary>
-        /// The layer containing the background color.
+        /// The layer containing the background color.<br/>
+        /// Used by "BGColorConverter" of the UndertaleModTool room editor.
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:173]: Put this into remarks please, not summary.
Also link to BGColorConverter via a cref attribute

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 2]
```diff
@@ -421,12 +427,30 @@ public class Background : UndertaleObject, INotifyPropertyChanged
             private UndertaleRoom _ParentRoom;
 
             /// <summary>
-            /// The room parent this background belongs to.
+            /// The room parent this background belongs to.<br/>
+            /// Set by <see cref="SetupRoom(bool)"/>.
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:431]: Unnecessary. If someone wants to see by what it's set, they can just "search all references." It's also not something that should be put into documentation.

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 3]
```diff
@@ -421,12 +427,30 @@ public class Background : UndertaleObject, INotifyPropertyChanged
...
             /// </summary>
+            /// <remarks>
+            /// This attribute is UMT-only and does not exist in GameMaker.
+            /// </remarks>
             public UndertaleRoom ParentRoom { get => _ParentRoom; set { _ParentRoom = value; OnPropertyChanged(); UpdateStretch(); } }
 
-            //TODO:
+            /// <summary>
+            /// The calculated horizontal render scale for the background texture.<br/>
+            /// Used in the UndertaleModTool room editor.
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:440]: This sentence is unnecessary. An UndertaleRoom attribute being used by the room editor is obvious.

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 4]
```diff
@@ -421,12 +427,30 @@ public class Background : UndertaleObject, INotifyPropertyChanged
...
+            /// </summary>
+            /// <remarks>
+            /// This attribute is UMT-only and does not exist in GameMaker.
+            /// </remarks>
             public float CalcScaleX { get; set; } = 1;
+
+            /// <summary>
+            /// The calculated vertical render scale for the background texture.<br/>
+            /// Used in the UndertaleModTool room editor.
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:449]: This sentence is unnecessary. An UndertaleRoom attribute being used by the room editor is obvious.

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 5]
```diff
@@ -477,13 +501,19 @@ public class Background : UndertaleObject, INotifyPropertyChanged
             public bool Stretch { get => _Stretch; set { _Stretch = value; OnPropertyChanged(); UpdateStretch(); } }
 
             /// <summary>
-            /// Whether this background is tiled horizontally.
+            /// A wrapper of <see cref="TileX"/> that indicates whether this background is tiled horizontally.
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:504]:
```suggestion
            /// Indicates whether this background is tiled horizontally.
```

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 6]
```diff
@@ -477,13 +501,19 @@ public class Background : UndertaleObject, INotifyPropertyChanged
...
             /// </summary>
+            /// <remarks>
+            /// This attribute is UMT-only and does not exist in GameMaker.
+            /// </remarks>
             public bool TiledHorizontally { get => TileX > 0; set { TileX = value ? 1 : 0; OnPropertyChanged(); } }
 
             /// <summary>
-            /// Whether this background is tiled vertically.
+            /// A wrapper of <see cref="TileY"/> that indicates whether this background is tiled vertically.
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:512]:
```suggestion
            /// Indicates whether this background is tiled vertically.
```

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 7]
```diff
@@ -756,29 +786,49 @@ protected void OnPropertyChanged([CallerMemberName] string name = null)
             }
 
             /// <summary>
-            /// The opposite angle of the current rotation.
+            /// A wrapper of <see cref="Rotation"/> that returns an opposite angle of the current rotation.
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:789]:
```suggestion
            /// The opposite angle of the current rotation.
```

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 8]
```diff
@@ -756,29 +786,49 @@ protected void OnPropertyChanged([CallerMemberName] string name = null)
...
             /// </summary>
+            /// <remarks>
+            /// This attribute is UMT-only and does not exist in GameMaker.
+            /// </remarks>
             public float OppositeRotation => 360F - (Rotation % 360);
 
             /// <summary>
-            /// A horizontal offset used for proper game object display in the UndertaleModTool room editor.
+            /// A horizontal offset relative to top-left corner of the game object.<br/>
+            /// Used for proper game object rotation display in the UndertaleModTool room editor and in <see cref="XOffset"/>.
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:798]: This should be put into remarks

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 9]
```diff
@@ -756,29 +786,49 @@ protected void OnPropertyChanged([CallerMemberName] string name = null)
...
-            public int XOffset => ObjectDefinition?.Sprite != null
-                                  ? X - ObjectDefinition.Sprite.OriginX + (ObjectDefinition.Sprite.Textures.ElementAtOrDefault(ImageIndex)?.Texture?.TargetX ?? 0)
-                                  : X;
+            public int SpriteXOffset => ObjectDefinition?.Sprite != null
+                                        ? (-1 * ObjectDefinition.Sprite.OriginXWrapper) + (ObjectDefinition.Sprite.Textures.ElementAtOrDefault(ImageIndex)?.Texture?.TargetX ?? 0)
+                                        : 0;
+
+            /// <summary>
+            /// A vertical offset relative to top-left corner of the game object.<br/>
+            /// Used for proper game object rotation display in the UndertaleModTool room editor and in <see cref="YOffset"/>.
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:809]: This should be put into remarks

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 10]
```diff
@@ -838,9 +888,14 @@ public override string ToString()
         public class Tile : UndertaleObject, RoomObject, INotifyPropertyChanged
         {
             /// <summary>
-            /// Whether this tile is from an asset layer. Game Maker Studio: 2 exclusive.
+            /// Whether this tile is from an asset layer.<br/>
+            /// Equals true if it's Game Maker Studio: 2.
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:892]: Is this true in *all* GMS2 games?

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 11]
```diff
@@ -865,8 +920,8 @@ public class Tile : UndertaleObject, RoomObject, INotifyPropertyChanged
             public UndertaleSprite SpriteDefinition { get => _spriteDefinition.Resource; set { _spriteDefinition.Resource = value; OnPropertyChanged(); OnPropertyChanged("ObjectDefinition"); } }
 
             /// <summary>
-            /// From which object this tile stems from.
-            /// Will return a <see cref="UndertaleBackground"/> if <see cref="spriteMode"/> is disabled, a <see cref="UndertaleSprite"/> if it's enabled.
+            /// From which object this tile stems from.<br/>
+            /// Will return a <see cref="UndertaleBackground"/> if <see cref="spriteMode"/> is true, a <see cref="UndertaleSprite"/> if it's false.
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:924]: Use langwords for true and false please.

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 12]
```diff
@@ -913,6 +968,12 @@ public class Tile : UndertaleObject, RoomObject, INotifyPropertyChanged
             //TODO?
             public uint Color { get; set; } = 0xFFFFFFFF;
 
+            /// <summary>
+            /// Returns a texture page item of the tile.
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:972]: *a* or *the*?

**Review by Miepee — COMMENTED** [review]
Didnt have time to review everything right now, will review more later

File: UndertaleModLib/Models/UndertaleRoom.cs (hunk 1 above)
Comment (VladiStep) [reply UndertaleModLib/Models/UndertaleRoom.cs:173]: Okay.
I've tried to add `<see cref="">`, but it doesn't resolve.

File: UndertaleModLib/Models/UndertaleRoom.cs (hunk 11 above)
Comment (VladiStep) [reply UndertaleModLib/Models/UndertaleRoom.cs:924]: Yeah, I thought about it.

File: UndertaleModLib/Models/UndertaleRoom.cs (hunk 10 above)
Comment (VladiStep) [reply UndertaleModLib/Models/UndertaleRoom.cs:892]: Yes.
`spriteMode = reader.undertaleData.GeneralInfo.Major >= 2;`

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 13]
```diff
@@ -166,20 +166,26 @@ public enum RoomEntryFlags : uint
...
+        /// This attribute is UMT-only and does not exist in GameMaker.
+        /// </remarks>
+        public Layer BGColorLayer
+        {
+            get
+            {
+                return _layers?.Where(l => l.LayerType is LayerType.Background
+                                        && l.BackgroundData.Sprite is null
+                                        && l.BackgroundData.Color != 0)
+                               .OrderBy(l => l?.LayerDepth ?? 0)
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:185]:
```suggestion
                               .OrderBy(l => l.LayerDepth ?? 0)
```
the layers are known to not be null there.

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 14]
```diff
@@ -758,27 +787,47 @@ protected void OnPropertyChanged([CallerMemberName] string name = null)
...
+            /// This attribute is UMT-only and does not exist in GameMaker.
+            /// </remarks>
             public float OppositeRotation => 360F - (Rotation % 360);
 
             /// <summary>
-            /// A horizontal offset used for proper game object display in the UndertaleModTool room editor.
+            /// A horizontal offset relative to top-left corner of the game object.
             /// </summary>
             /// <remarks>
+            /// Used for proper game object rotation display in the room editor and in <see cref="XOffset"/>.<br/>
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:799]:
```suggestion
            /// Used for proper game object rotation display in the room editor and for <see cref="XOffset"/>.<br/>
```

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 15]
```diff
@@ -758,27 +787,47 @@ protected void OnPropertyChanged([CallerMemberName] string name = null)
...
+            public int SpriteXOffset => ObjectDefinition?.Sprite != null
+                                        ? (-1 * ObjectDefinition.Sprite.OriginXWrapper) + (ObjectDefinition.Sprite.Textures.ElementAtOrDefault(ImageIndex)?.Texture?.TargetX ?? 0)
+                                        : 0;
 
             /// <summary>
-            /// A vertical offset used for proper game object display in the UndertaleModTool room editor.
+            /// A vertical offset relative to top-left corner of the game object.
             /// </summary>
             /// <remarks>
+            /// Used for proper game object rotation display in the room editor and in <see cref="YOffset"/>.<br/>
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:810]:
```suggestion
            /// Used for proper game object rotation display in the room editor and for <see cref="YOffset"/>.<br/>
```

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 16]
```diff
@@ -838,9 +887,14 @@ public override string ToString()
         public class Tile : UndertaleObject, RoomObject, INotifyPropertyChanged
         {
             /// <summary>
-            /// Whether this tile is from an asset layer. Game Maker Studio: 2 exclusive.
+            /// Whether this tile is from an asset layer.<br/>
+            /// Equals true if it's Game Maker Studio: 2.
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:891]:
```suggestion
            /// <see langword="true"/> for GameMaker Studio: 2 games, otherwise <see langword="false"/>.
```

Also, wonder if this attribute's setter should be limited. Since being able to just change it will very likely cause some issues.

File: UndertaleModLib/Models/UndertaleRoom.cs [hunk 17]
```diff
@@ -1415,12 +1481,15 @@ public int WrappedFrameIndex
...
-                                  : Y;
+
+            public int SpriteXOffset => Sprite != null
+                                        ? (-1 * Sprite.OriginXWrapper) + (Sprite.Textures.ElementAtOrDefault(WrappedFrameIndex)?.Texture?.TargetX ?? 0)
+                                        : 0;
+            public int SpriteYOffset => Sprite != null
+                                        ? (-1 * Sprite.OriginYWrapper) + (Sprite.Textures.ElementAtOrDefault(WrappedFrameIndex)?.Texture?.TargetY ?? 0)
+                                        : 0;
+            public int XOffset => X + SpriteXOffset;
+            public int YOffset => Y + SpriteYOffset;
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleRoom.cs:1492]: Mind adding documentation for these?

File: UndertaleModLib/Models/UndertaleSprite.cs [hunk 18]
```diff
@@ -114,6 +114,42 @@ public class UndertaleSprite : UndertaleNamedResource, PrePaddedObject, INotifyP
         /// </summary>
         public int OriginY { get; set; }
 
+        /// <summary>
+        /// A <see cref="OriginX"/> wrapper than also sets horizontal origin of <see cref="V2Sequence"/>.
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleSprite.cs:118]:
```suggestion
        /// A <see cref="OriginX"/> wrapper that also sets <see cref="V2Sequence.OriginX"/> accordingly.
```

File: UndertaleModLib/Models/UndertaleSprite.cs [hunk 19]
```diff
@@ -114,6 +114,42 @@ public class UndertaleSprite : UndertaleNamedResource, PrePaddedObject, INotifyP
...
+        /// </summary>
+        /// <remarks>
+        /// This attribute is used only in UndertaleModTool and doesn't exist in GameMaker.
+        /// </remarks>
+        public int OriginXWrapper
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleSprite.cs:123]: Hm, in order to not have anyone use originX and thus forgetting to update V2Sequence.OriginX as well, shouldn't OriginX just be a private attribute and renamed to something else while this gets then renamed to OriginX?

File: UndertaleModLib/Models/UndertaleSprite.cs [hunk 20]
```diff
@@ -114,6 +114,42 @@ public class UndertaleSprite : UndertaleNamedResource, PrePaddedObject, INotifyP
...
+            {
+                OriginX = value;
+
+                if (IsSpecialType && SVersion > 1 && V2Sequence is not null)
+                    V2Sequence.OriginX = value;
+            }
+        }
+
+        /// <summary>
+        /// A <see cref="OriginY"/> wrapper than also sets vertical origin of <see cref="V2Sequence"/>.
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleSprite.cs:136]:
```suggestion
        /// A <see cref="OriginY"/> wrapper that also sets <see cref="V2Sequence.OriginY"/> accordingly.
```

File: UndertaleModLib/Models/UndertaleSprite.cs [hunk 21]
```diff
@@ -114,6 +114,42 @@ public class UndertaleSprite : UndertaleNamedResource, PrePaddedObject, INotifyP
...
+        /// </summary>
+        /// <remarks>
+        /// This attribute is used only in UndertaleModTool and doesn't exist in GameMaker.
+        /// </remarks>
+        public int OriginYWrapper
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleSprite.cs:141]: See comment from above about OriginXWrapper

File: UndertaleModTool/Converters/UndertaleCachedImageLoader.cs [hunk 22]
```diff
@@ -281,7 +284,7 @@ public object Convert(object[] values, Type targetType, object parameter, Cultur
             if (values[0] is null) // tile
                 return null;
 
-            if ((uint)values[3] == 0 || (uint)values[4] == 0) // width, height
+            if ((uint)values[1] == 0 || (uint)values[2] == 0) // width, height
```
Comment (Miepee) [inline UndertaleModTool/Converters/UndertaleCachedImageLoader.cs:287]: Why were these changed? Whats the deal behind those

File: UndertaleModTool/Editors/UndertaleRoomEditor.xaml.cs [hunk 23]
```diff
@@ -1297,13 +1297,15 @@ private void AddSprite(Layer layer)
             {
                 // add pointer list if one doesn't already exist
                 layer.AssetsData.Sprites ??= new UndertalePointerList<SpriteInstance>();
+                
+                SpriteInstance sprInst = new();
+                string sprName = "graphic_" + ((uint)new Random().Next(-int.MaxValue, int.MaxValue)).ToString("X8");
```
Comment (Miepee) [inline UndertaleModTool/Editors/UndertaleRoomEditor.xaml.cs:1302]: Can you rename these to `spriteInstance` and `spriteName` respectively please?

**Review by Miepee — COMMENTED** [review]
Second round of reviews

File: UndertaleModLib/Models/UndertaleRoom.cs (hunk 16 above)
Comment (VladiStep) [reply UndertaleModLib/Models/UndertaleRoom.cs:891]: Regarding setter - `spriteMode` is public and has setter only for having an ability to make a copy of it, because room objects don't have `Clone()` method yet.

File: UndertaleModLib/Models/UndertaleRoom.cs (hunk 17 above)
Comment (VladiStep) [reply UndertaleModLib/Models/UndertaleRoom.cs:1492]: If I'll add that here, then I also should add descriptions to other properties as well.

Comment (Miepee) [reply UndertaleModLib/Models/UndertaleRoom.cs:1492]: Not necessarily, but would be nicer, yeah. 
If you plan to do that, maybe do that in another PR?

File: UndertaleModLib/Models/UndertaleRoom.cs (hunk 16 above)
Comment (Miepee) [reply UndertaleModLib/Models/UndertaleRoom.cs:891]: Ah, ok.

File: UndertaleModLib/Models/UndertaleSprite.cs (hunk 19 above)
Comment (VladiStep) [reply UndertaleModLib/Models/UndertaleSprite.cs:123]: Yeah, I'll consider that.

File: UndertaleModTool/Converters/UndertaleCachedImageLoader.cs (hunk 22 above)
Comment (VladiStep) [reply UndertaleModTool/Converters/UndertaleCachedImageLoader.cs:287]: It's related to the tile update fix _(see changes starting from line 1126 of "UndertaleRoomEditor.xaml")_.

File: UndertaleModLib/Models/UndertaleRoom.cs (hunk 17 above)
Comment (VladiStep) [reply UndertaleModLib/Models/UndertaleRoom.cs:1492]: Yeah, probably will do that.
