### PR TITLE
Fix images in the input text box.

### LINKED ISSUE #1590: The input text box (e.g. the "Enter your search" window) accepts images.
### Describe the bug

It's possible to insert images into the `TextInput` window (e.g. when you use "Search.csx" script), though it has no use.
image

### Reproducing steps

1. Open any script that requires some text input.
2. Copy an image to a clipboard.
3. Insert it to the text box.

### Setup Details

1. UTMT version - https://github.com/krzys-h/UndertaleModTool/commit/979db25e44c99ec41641f6b6b50b5949af6a679c

### PR DESCRIPTION
**Pull request by VladiStep**
## Description
Fixes #1590, also made changes in "TextInput.Designer.cs" that Visual Studio automatically applied (just some code optimizations like `this.property` -> `property`).

### CODE REVIEW

File: UndertaleModTool/Windows/TextInput.cs [hunk 1]
```diff
@@ -80,7 +80,7 @@ public TextInput(string message, string title, string defaultValue, bool allowMu
             label1.Text = message;
             richTextBox1.Multiline = AllowMultiline;
             richTextBox1.DetectUrls = false;
-            richTextBox1.LanguageOption = RichTextBoxLanguageOptions.UIFonts; //prevents the bug with Japanese characters
+            richTextBox1.LanguageOption = RichTextBoxLanguageOptions.UIFonts; // prevents the bug with Japanese characters
```
Comment (Miepee) [inline UndertaleModTool/Windows/TextInput.cs]: can you also uppercase the "Prevents" please? :)

File: UndertaleModTool/Windows/TextInput.cs [hunk 2]
```diff
@@ -100,7 +100,7 @@ public TextInput(string message, string title, string defaultValue, bool allowMu
 
         private void TextInput_Load(object sender, EventArgs e)
         {
-            richTextBox1.Clear(); //remove "Input text here"
+            richTextBox1.Clear(); // remove "Input text here"
```
Comment (Miepee) [inline UndertaleModTool/Windows/TextInput.cs]: ditto uppercase

File: UndertaleModTool/Windows/TextInput.cs [hunk 3]
```diff
@@ -111,14 +111,24 @@ private void TextInput_Load(object sender, EventArgs e)
 
             if (richTextBox1.ReadOnly)
             {
-                richTextBox1.BackColor = TextBoxBGColor; //restore color to default one.
+                richTextBox1.BackColor = TextBoxBGColor; // restore color to default one.
```
Comment (Miepee) [inline UndertaleModTool/Windows/TextInput.cs]: diito uppercase

File: UndertaleModTool/Windows/TextInput.cs [hunk 4]
```diff
@@ -111,14 +111,24 @@ private void TextInput_Load(object sender, EventArgs e)
...
             }
         }
 
         private void richTextBox1_TextChanged(object sender, EventArgs e)
         {
         }
+        private void richTextBox1_KeyDown(object sender, KeyEventArgs e)
+        {
+            // Prevent image pasting
+            if (e.Control && e.KeyCode == Keys.V)
```
Comment (Miepee) [inline UndertaleModTool/Windows/TextInput.cs:125]: this seems bad. is there no way to check whether the user has input a "paste" combination? because this might not be necessarily CTRL+V if you change the combo in windows, or have a different combo in linux and run via WINE.

File: UndertaleModTool/Windows/TextInput.cs (hunk 1 above)
Comment (Miepee) [reply UndertaleModTool/Windows/TextInput.cs]: nvm too early. can close this and the other 3

File: UndertaleModTool/Windows/TextInput.cs (hunk 4 above)
Comment (VladiStep) [reply UndertaleModTool/Windows/TextInput.cs:125]: Hmm, I didn't know that you can change that

Comment (VladiStep) [reply UndertaleModTool/Windows/TextInput.cs:125]: Wait, it seems you can't change that in Windows - https://answers.microsoft.com/en-us/windows/forum/all/need-to-change-the-shortcut-keys-for-copypaste/87583aa7-68c4-4b22-9cc0-d298b537a094.
Though, there is an alternative insert combination - `Shift+Insert`.

Also, are you sure that Wine doesn't emulate `Ctrl+V`?

Comment (VladiStep) [reply UndertaleModTool/Windows/TextInput.cs]: Anyway, I added the second combination, and I don't know a better way to detect the paste action there.

Comment (Miepee) [reply UndertaleModTool/Windows/TextInput.cs]: > it seems you can't change that in Windows 

You can: 
grafik
https://learn.microsoft.com/en-us/windows/powertoys/keyboard-manager

> Also, are you sure that Wine doesn't emulate Ctrl+V?

WINE passes the paste signal through. And linux DE's let you customize anything you want as paste. from META+V to F1 to CTRL+SHIFT+INSERT+PAGEUP+F12+F1+Z+SPACE

Comment (Miepee) [reply UndertaleModTool/Windows/TextInput.cs]: cant we somehow intercept the paste event, and delete image contents instead? Am not a fan of hardcoding key combinations.

Comment (Miepee) [reply UndertaleModTool/Windows/TextInput.cs]: can you please unresolve this? @VladiStep

Comment (VladiStep) [reply UndertaleModTool/Windows/TextInput.cs]: I just checked, PowerToys sends `Ctrl+V` to the app in the end anyway, so it doesn't count (the fix still works).

Comment (Miepee) [reply UndertaleModTool/Windows/TextInput.cs]: Meh. Still very much not a fan of harcoding key combinations. Can you at least add a small comment there?

**Review by Miepee — APPROVED** [review]
