### PR TITLE
Calculate length of texture data during serialization instead of writing a set value & Update ImportGMS2FontData

### LINKED ISSUE #1042: The "TextureBlockSize" value of embedded textures is not dynamically calculated
### Describe the bug

A extra value was introduced in GM 2022.3 to texture pages in the TXTR chuck, which is the size of the texture data that the texture page contains.
For what the value is supposed to be, and since you can replace the texture data to anything through the ModLib interface, I suppose the value should be dynamically calculated during the serialization of texture pages. However, it's just read into the TextureBlockSize variable when texture pages are deserialized, which is simply written into the data file intact when texture pages are serialized. It's never recalculated in any way when the texture data is replaced, and for new, programmatically created UndertaleEmbeddedTexture instances, it's just set to 0.

The obvious effect of this is when new texture pages are added to data file, and are used in any way, graphics created from the page items in the texture page will not show up when the data file is ran. This visibly affects the NewTexturePacker script, which recreates texture pages anew; when it is ran on a GM 2022.3 game that uses the QOI image format, and the game is ran, no sprites or fonts will show up at all.

### Reproducing steps

1. Open a data file made in GM 2022.3
2. Add a new texture page to the file programmatically, and add data to it
3. Save the file
4. Reopen the newly saved file
5. Poke the new texture page and find it's TextureBlockSize is zero

or:

1. Open a 2022.3 game that uses the QOI image format such as HoloCure
2. Run NewTexturePacker.csx
3. Save game and run
4. Observe that no sprites and fonts show up

### Setup Details

1. UndertaleModTool version: commit b8a11a2
2. Operating system: Windows 11
3. Game: [HoloCure](https://kay-yu.itch.io/holocure)

### PR DESCRIPTION
**Pull request by Dobby233Liu**
## Description
Fixes #1042

### CODE REVIEW

**Comment by Dobby233Liu** [comment]
I should also check if the value is written with games that use PNG

**Comment by Jacky720** [comment]
Uh, won't this not work on pre-2022.3 games?

**Comment by Dobby233Liu** [comment]
Hmm, I haven't checked

File: UndertaleModLib/Models/UndertaleEmbeddedTexture.cs [hunk 1]
```diff
@@ -35,24 +35,34 @@ public class UndertaleEmbeddedTexture : UndertaleNamedResource, IDisposable
...
         writer.Write(Scaled);
         if (writer.undertaleData.GeneralInfo.Major >= 2)
             writer.Write(GeneratedMips);
-        if (writer.undertaleData.GM2022_3)
-            writer.Write(TextureBlockSize);
+        // Write a placeholder for the texture blob size,
+        // so we can overwrite this with the actual value
+        // later
+        _TextureBlockSizeLocation = writer.Position;
+        writer.Write((uint)0);
```
Comment (Dobby233Liu) [inline UndertaleModLib/Models/UndertaleEmbeddedTexture.cs:65]: I forgot the 2022.3 check wtf

File: UndertaleModLib/Models/UndertaleEmbeddedTexture.cs [hunk 2]
```diff
@@ -77,7 +87,18 @@ public void SerializeBlob(UndertaleWriter writer)
         while (writer.Position % 0x80 != 0)
             writer.Write((byte)0);
 
+        var objStartPos = writer.Position;
         writer.WriteUndertaleObject(TextureData);
+        var objEndPos = writer.Position;
+
+        uint length = writer.Position - objStartPos;
```
Comment (Dobby233Liu) [inline UndertaleModLib/Models/UndertaleEmbeddedTexture.cs:94]: There should be one here too

**Review by Dobby233Liu — COMMENTED** [review]
Oh lmao

**Comment by Dobby233Liu** [comment]
Added 2022.3 checks, should be correct now

> I should also check if the value is written for games that use PNG

Also we still need to check this

File: UndertaleModLib/Models/UndertaleEmbeddedTexture.cs [hunk 3]
```diff
@@ -35,10 +35,16 @@ public class UndertaleEmbeddedTexture : UndertaleNamedResource, IDisposable
     public uint GeneratedMips { get; set; }
 
     /// <summary>
-    /// TODO: something. <br/>
+    /// The size of the texture data in the embedded image. <br/>
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleEmbeddedTexture.cs:38]: Size in what? bytes?

File: UndertaleModLib/Models/UndertaleEmbeddedTexture.cs [hunk 4]
```diff
@@ -35,10 +35,16 @@ public class UndertaleEmbeddedTexture : UndertaleNamedResource, IDisposable
...
     /// GameMaker: Studio 2 only.
     /// </summary>
-    public uint TextureBlockSize { get; set; }
+    private uint _TextureBlockSize { get; set; }
+
+    /// <summary>
+    /// The position of the TextureBlockSize value to be overwritten in Serialize. <br/>
+    /// Only used internally in UMTLib for GM 2022.3 support.
+    /// </summary>
+    internal uint _TextureBlockSizeLocation { get; set; }
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleEmbeddedTexture.cs:47]: If it's only used internally, change it to `private` please.

File: UndertaleModLib/Models/UndertaleEmbeddedTexture.cs [hunk 5]
```diff
@@ -35,10 +35,16 @@ public class UndertaleEmbeddedTexture : UndertaleNamedResource, IDisposable
...
     /// <summary>
-    /// TODO: something. <br/>
+    /// The size of the texture data in the embedded image. <br/>
     /// GameMaker: Studio 2 only.
     /// </summary>
-    public uint TextureBlockSize { get; set; }
+    private uint _TextureBlockSize { get; set; }
+
+    /// <summary>
+    /// The position of the TextureBlockSize value to be overwritten in Serialize. <br/>
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleEmbeddedTexture.cs:44]: Adress TextureBlockSize via cref

File: UndertaleModLib/Models/UndertaleEmbeddedTexture.cs [hunk 6]
```diff
@@ -52,7 +58,13 @@ public void Serialize(UndertaleWriter writer)
         if (writer.undertaleData.GeneralInfo.Major >= 2)
             writer.Write(GeneratedMips);
         if (writer.undertaleData.GM2022_3)
-            writer.Write(TextureBlockSize);
+        {
+            // Write a placeholder for the texture blob size,
+            // so we can overwrite this with the actual value
+            // later
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleEmbeddedTexture.cs:64]: Can you put the later word on the previous line?

File: UndertaleModLib/Models/UndertaleEmbeddedTexture.cs [hunk 7]
```diff
@@ -77,7 +89,21 @@ public void SerializeBlob(UndertaleWriter writer)
...
+        var objStartPos = writer.Position;
         writer.WriteUndertaleObject(TextureData);
+        var objEndPos = writer.Position;
+
+        if (writer.undertaleData.GM2022_3)
+        {
+            uint length = writer.Position - objStartPos;
+            _TextureBlockSize = length;
+            // Move to the placeholder zero value wrote
+            // in Serialize
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleEmbeddedTexture.cs:101]: Can you put this onto one line?

File: UndertaleModLib/Models/UndertaleEmbeddedTexture.cs [hunk 8]
```diff
@@ -35,10 +35,16 @@ public class UndertaleEmbeddedTexture : UndertaleNamedResource, IDisposable
     public uint GeneratedMips { get; set; }
 
     /// <summary>
-    /// TODO: something. <br/>
+    /// The size of the texture data in the embedded image. <br/>
     /// GameMaker: Studio 2 only.
     /// </summary>
-    public uint TextureBlockSize { get; set; }
+    private uint _TextureBlockSize { get; set; }
```
Comment (Miepee) [inline UndertaleModLib/Models/UndertaleEmbeddedTexture.cs:41]: Is this an UMT-only attribute, or is this actually saved into the data.win?

File: UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx [hunk 9]
```diff
@@ -38,23 +38,38 @@ string textureSourcePath = Path.Combine(Path.GetDirectoryName(importFile), fontN
 if (!File.Exists(textureSourcePath))
     throw new ScriptException("The font texture file " + textureSourcePath + " doesn't exist.");
 
+UndertaleTextureGroupInfo defaultTexGroup = null;
+bool disappearMigitation = Data.GM2022_3;
```
Comment (Miepee) [inline UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx:42]: `disappearMitigation`? can you explain the name here?

File: UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx [hunk 10]
```diff
@@ -38,23 +38,38 @@ string textureSourcePath = Path.Combine(Path.GetDirectoryName(importFile), fontN
...
     Data.Fonts.Add(font);
+    if (disappearMigitation)
+        defaultTexGroup.Fonts.Add(new UndertaleResourceById<UndertaleFont, UndertaleChunkFONT>() { Resource = font });
 }
 
 Bitmap textureBitmap = new Bitmap(textureSourcePath);
+textureBitmap.SetResolution(96.0F, 96.0F); // dpi fix
 UndertaleEmbeddedTexture texture = new UndertaleEmbeddedTexture();
-texture.Name = Data.Strings.MakeString("Texture " + Data.EmbeddedTextures.Count); // ???
+texture.Name = new UndertaleString("Texture " + Data.EmbeddedTextures.Count); // ???
```
Comment (Miepee) [inline UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx:65]: Why do you create a new UndertaleString instead of using MakeString?

File: UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx [hunk 11]
```diff
@@ -38,23 +38,38 @@ string textureSourcePath = Path.Combine(Path.GetDirectoryName(importFile), fontN
...
 texture.TextureData.TextureBlob = File.ReadAllBytes(textureSourcePath);
 Data.EmbeddedTextures.Add(texture);
+if (disappearMigitation)
+    defaultTexGroup.TexturePages.Add(new UndertaleResourceById<UndertaleEmbeddedTexture, UndertaleChunkTXTR>() { Resource = texture });
 
 UndertaleTexturePageItem texturePageItem = new UndertaleTexturePageItem();
-texturePageItem.Name = Data.Strings.MakeString("PageItem " + Data.TexturePageItems.Count); // ???
+texturePageItem.Name = new UndertaleString("PageItem " + Data.TexturePageItems.Count); // ???
```
Comment (Miepee) [inline UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx:72]: Same as above

File: UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx [hunk 12]
```diff
@@ -89,17 +103,19 @@ if (fontData.ContainsKey("ascender"))
...
+uint rangeEnd = 0;
 foreach (JObject range in fontData["ranges"].Values<JObject>())
 {
-    var rangeStart = (ushort)range["lower"];
-    var rangeEnd = (uint)range["upper"];
-    if (font.RangeStart > rangeStart)
-        font.RangeStart = rangeStart;
-    if (font.RangeEnd > rangeEnd)
-        font.RangeEnd = rangeEnd;
+    var rangeStartChk = (ushort)range["lower"];
```
Comment (Miepee) [inline UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx:110]: What's Chk short for?

**Review by Miepee — COMMENTED** [review]
Don't have the full context right now: When is the normal serialize function called vs serialize blob?

File: UndertaleModLib/Models/UndertaleEmbeddedTexture.cs (hunk 3 above)
Comment (Dobby233Liu) [reply UndertaleModLib/Models/UndertaleEmbeddedTexture.cs:38]:
```suggestion
    /// The size of the texture data in the embedded image in bytes. <br/>
```

File: UndertaleModLib/Models/UndertaleEmbeddedTexture.cs (hunk 8 above)
Comment (Dobby233Liu) [reply UndertaleModLib/Models/UndertaleEmbeddedTexture.cs:41]: It's in the data file so definitely not UMT-only, I think the variable is no longer used in UML though

File: UndertaleModLib/Models/UndertaleEmbeddedTexture.cs (hunk 4 above)
Comment (Dobby233Liu) [reply UndertaleModLib/Models/UndertaleEmbeddedTexture.cs:47]:
```suggestion
    private uint _TextureBlockSizeLocation { get; set; }
```

File: UndertaleModLib/Models/UndertaleEmbeddedTexture.cs (hunk 8 above)
Comment (Miepee) [reply UndertaleModLib/Models/UndertaleEmbeddedTexture.cs:41]: Cool, just wanted to make sure.

File: UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx (hunk 10 above)
Comment (Dobby233Liu) [reply UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx:65]: Because every other script did that, IDK why a UndertaleString was used anyway

Comment (Miepee) [reply UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx:65]: You should probably revert that then, as MakeString is safer.

File: UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx (hunk 9 above)
Comment (Miepee) [reply UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx:42]: A small comment would be nice then explaining that.

File: UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx (hunk 10 above)
Comment (Dobby233Liu) [reply UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx:65]: I mean the other scripts don't add the new string to Data.Strings like MakeString does, I don't think anything requires the "name" to be actually in data.win too

File: UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx (hunk 12 above)
Comment (Dobby233Liu) [reply UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx:110]: `Check` IIRC, I'm probably going to drop these variables though

File: UndertaleModLib/Models/UndertaleEmbeddedTexture.cs (hunk 5 above)
Comment (Dobby233Liu) [reply UndertaleModLib/Models/UndertaleEmbeddedTexture.cs:44]:
```suggestion
    /// The position of the placeholder <see cref="_TextureBlockSize">TextureBlockSize</see> value
    /// to be overwritten in Serialize. <br/>
```
istg if this sent earlier

File: UndertaleModLib/Models/UndertaleEmbeddedTexture.cs (hunk 6 above)
Comment (Dobby233Liu) [reply UndertaleModLib/Models/UndertaleEmbeddedTexture.cs:64]:
```suggestion
test
```

File: UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx (hunk 10 above)
Comment (Miepee) [reply UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx:65]: Ah wait, it's for the texture name. Yeah, carry on then.

File: UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx [hunk 13]
```diff
@@ -7,54 +7,106 @@ using System.Collections;
 using System.Collections.Generic;
```
Comment (Dobby233Liu) [inline UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx:7]: Diff is messy due of the random reorganizations, apologies

**Comment by Grossley** [comment]
What is the status of this pull request?

File: UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx [hunk 14]
```diff
@@ -7,54 +7,106 @@ using System.Collections;
...
+            throw new ScriptException("The default texture group doesn't exist??? (this shouldn't happen)");
+        fontTexGroup.Fonts.Add(new UndertaleResourceById<UndertaleFont, UndertaleChunkFONT>() { Resource = font });
+    }
 }
+else if (attemptToFixFontNotAppearing)
+{
+    // Try to find the texgroup that the font belongs to
+    // Scariest LINQ query I've ever written (yet)
+    fontTexGroup = Data.TextureGroupInfo
+        .Where(t => t.Fonts.ToList().Exists(f => f.Resource == font))
```
Comment (VladiStep) [inline UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx:84]:
```suggestion
        .Where(t => t.Fonts.Any(f => f.Resource == font))
```

File: UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx [hunk 15]
```diff
@@ -7,54 +7,106 @@ using System.Collections;
...
+        .DefaultIfEmpty(fontTexGroup)
+        .FirstOrDefault();
+    if (fontTexGroup == null)
+        throw new ScriptException("Existing font doesn't belong to any texture group AND the default texture group doesn't exist??? (this shouldn't happen)");
+    // Failsafe - put it in Default if it's not in there
+    if (!fontTexGroup.Fonts.ToList().Exists(f => f.Resource == font))
```
Comment (VladiStep) [inline UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx:90]:
```suggestion
    if (!fontTexGroup.Fonts.Any(f => f.Resource == font))
```

File: UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx (hunk 14 above)
Comment (VladiStep) [reply UndertaleModTool/Scripts/Community Scripts/ImportGMS2FontData.csx:84]: No need to convert that to a list.

**Review by VladiStep — CHANGES_REQUESTED** [review]

**Review by VladiStep — APPROVED** [review]
